In [7]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("D3 P6 R2.csv")
df.head()

V        I  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5
0  4.00  0.00171         NaN         NaN         NaN         NaN
1  3.98  0.00167         NaN         NaN         NaN         NaN
2  3.96  0.00164         NaN         NaN         NaN         NaN
3  3.94  0.00163         NaN         NaN         NaN         NaN
4  3.92  0.00161         NaN         NaN         NaN         NaN

In [5]:
task = df.iloc[:,0:2]
task

V             I
0    4.00  1.710000e-03
1    3.98  1.670000e-03
2    3.96  1.640000e-03
3    3.94  1.630000e-03
4    3.92  1.610000e-03
..    ...           ...
196  0.08  1.240000e-06
197  0.06  8.940000e-07
198  0.04  5.830000e-07
199  0.02  2.870000e-07
200  0.00  1.040000e-10

[201 rows x 2 columns]

In [8]:
task1= np.array(task)
task1

array([[4.00e+00, 1.71e-03],
       [3.98e+00, 1.67e-03],
       [3.96e+00, 1.64e-03],
       [3.94e+00, 1.63e-03],
       [3.92e+00, 1.61e-03],
       [3.90e+00, 1.56e-03],
       [3.88e+00, 1.55e-03],
       [3.86e+00, 1.51e-03],
       [3.84e+00, 1.48e-03],
       [3.82e+00, 1.48e-03],
       [3.80e+00, 1.44e-03],
       [3.78e+00, 1.42e-03],
       [3.76e+00, 1.40e-03],
       [3.74e+00, 1.37e-03],
       [3.72e+00, 1.36e-03],
       [3.70e+00, 1.33e-03],
       [3.68e+00, 1.30e-03],
       [3.66e+00, 1.27e-03],
       [3.64e+00, 1.25e-03],
       [3.62e+00, 1.24e-03],
       [3.60e+00, 1.22e-03],
       [3.58e+00, 1.19e-03],
       [3.56e+00, 1.19e-03],
       [3.54e+00, 1.16e-03],
       [3.52e+00, 1.14e-03],
       [3.50e+00, 1.12e-03],
       [3.48e+00, 1.09e-03],
       [3.46e+00, 1.08e-03],
       [3.44e+00, 1.07e-03],
       [3.42e+00, 1.06e-03],
       [3.40e+00, 1.04e-03],
       [3.38e+00, 1.02e-03],
       [3.36e+00, 1.01e-03],
       [3.34e+00, 9.79e-04],
       [3.32e+

In [9]:
I= np.array(task["I"])
I

array([1.71e-03, 1.67e-03, 1.64e-03, 1.63e-03, 1.61e-03, 1.56e-03,
       1.55e-03, 1.51e-03, 1.48e-03, 1.48e-03, 1.44e-03, 1.42e-03,
       1.40e-03, 1.37e-03, 1.36e-03, 1.33e-03, 1.30e-03, 1.27e-03,
       1.25e-03, 1.24e-03, 1.22e-03, 1.19e-03, 1.19e-03, 1.16e-03,
       1.14e-03, 1.12e-03, 1.09e-03, 1.08e-03, 1.07e-03, 1.06e-03,
       1.04e-03, 1.02e-03, 1.01e-03, 9.79e-04, 9.70e-04, 9.59e-04,
       9.40e-04, 9.22e-04, 9.08e-04, 8.98e-04, 8.87e-04, 8.71e-04,
       8.59e-04, 8.46e-04, 8.33e-04, 8.25e-04, 8.15e-04, 8.06e-04,
       7.98e-04, 7.93e-04, 7.83e-04, 7.76e-04, 7.66e-04, 7.54e-04,
       7.40e-04, 7.37e-04, 7.28e-04, 7.18e-04, 7.11e-04, 7.00e-04,
       6.94e-04, 6.85e-04, 6.79e-04, 6.69e-04, 6.60e-04, 6.55e-04,
       6.50e-04, 6.38e-04, 6.28e-04, 6.19e-04, 6.09e-04, 6.02e-04,
       5.98e-04, 5.87e-04, 5.76e-04, 5.68e-04, 5.60e-04, 5.52e-04,
       5.44e-04, 5.36e-04, 5.30e-04, 5.22e-04, 5.12e-04, 5.05e-04,
       4.95e-04, 4.89e-04, 4.82e-04, 4.75e-04, 4.67e-04, 4.56e

In [10]:
J = I/0.000006
J = np.array(J)
J

array([2.85000000e+02, 2.78333333e+02, 2.73333333e+02, 2.71666667e+02,
       2.68333333e+02, 2.60000000e+02, 2.58333333e+02, 2.51666667e+02,
       2.46666667e+02, 2.46666667e+02, 2.40000000e+02, 2.36666667e+02,
       2.33333333e+02, 2.28333333e+02, 2.26666667e+02, 2.21666667e+02,
       2.16666667e+02, 2.11666667e+02, 2.08333333e+02, 2.06666667e+02,
       2.03333333e+02, 1.98333333e+02, 1.98333333e+02, 1.93333333e+02,
       1.90000000e+02, 1.86666667e+02, 1.81666667e+02, 1.80000000e+02,
       1.78333333e+02, 1.76666667e+02, 1.73333333e+02, 1.70000000e+02,
       1.68333333e+02, 1.63166667e+02, 1.61666667e+02, 1.59833333e+02,
       1.56666667e+02, 1.53666667e+02, 1.51333333e+02, 1.49666667e+02,
       1.47833333e+02, 1.45166667e+02, 1.43166667e+02, 1.41000000e+02,
       1.38833333e+02, 1.37500000e+02, 1.35833333e+02, 1.34333333e+02,
       1.33000000e+02, 1.32166667e+02, 1.30500000e+02, 1.29333333e+02,
       1.27666667e+02, 1.25666667e+02, 1.23333333e+02, 1.22833333e+02,
      

In [12]:
J = pd.DataFrame(J)
J.columns = ['J']
J.head()

J
0  285.000000
1  278.333333
2  273.333333
3  271.666667
4  268.333333

In [13]:
task2=task.join(J,lsuffix="_left")
task2

V             I           J
0    4.00  1.710000e-03  285.000000
1    3.98  1.670000e-03  278.333333
2    3.96  1.640000e-03  273.333333
3    3.94  1.630000e-03  271.666667
4    3.92  1.610000e-03  268.333333
..    ...           ...         ...
196  0.08  1.240000e-06    0.206667
197  0.06  8.940000e-07    0.149000
198  0.04  5.830000e-07    0.097167
199  0.02  2.870000e-07    0.047833
200  0.00  1.040000e-10    0.000017

[201 rows x 3 columns]

In [14]:
V=np.array(task['V'])
V

array([4.  , 3.98, 3.96, 3.94, 3.92, 3.9 , 3.88, 3.86, 3.84, 3.82, 3.8 ,
       3.78, 3.76, 3.74, 3.72, 3.7 , 3.68, 3.66, 3.64, 3.62, 3.6 , 3.58,
       3.56, 3.54, 3.52, 3.5 , 3.48, 3.46, 3.44, 3.42, 3.4 , 3.38, 3.36,
       3.34, 3.32, 3.3 , 3.28, 3.26, 3.24, 3.22, 3.2 , 3.18, 3.16, 3.14,
       3.12, 3.1 , 3.08, 3.06, 3.04, 3.02, 3.  , 2.98, 2.96, 2.94, 2.92,
       2.9 , 2.88, 2.86, 2.84, 2.82, 2.8 , 2.78, 2.76, 2.74, 2.72, 2.7 ,
       2.68, 2.66, 2.64, 2.62, 2.6 , 2.58, 2.56, 2.54, 2.52, 2.5 , 2.48,
       2.46, 2.44, 2.42, 2.4 , 2.38, 2.36, 2.34, 2.32, 2.3 , 2.28, 2.26,
       2.24, 2.22, 2.2 , 2.18, 2.16, 2.14, 2.12, 2.1 , 2.08, 2.06, 2.04,
       2.02, 2.  , 1.98, 1.96, 1.94, 1.92, 1.9 , 1.88, 1.86, 1.84, 1.82,
       1.8 , 1.78, 1.76, 1.74, 1.72, 1.7 , 1.68, 1.66, 1.64, 1.62, 1.6 ,
       1.58, 1.56, 1.54, 1.52, 1.5 , 1.48, 1.46, 1.44, 1.42, 1.4 , 1.38,
       1.36, 1.34, 1.32, 1.3 , 1.28, 1.26, 1.24, 1.22, 1.2 , 1.18, 1.16,
       1.14, 1.12, 1.1 , 1.08, 1.06, 1.04, 1.02, 1.

In [15]:
V_square = V**2
V_square = np.array(V_square)
V_square

array([1.60000e+01, 1.58404e+01, 1.56816e+01, 1.55236e+01, 1.53664e+01,
       1.52100e+01, 1.50544e+01, 1.48996e+01, 1.47456e+01, 1.45924e+01,
       1.44400e+01, 1.42884e+01, 1.41376e+01, 1.39876e+01, 1.38384e+01,
       1.36900e+01, 1.35424e+01, 1.33956e+01, 1.32496e+01, 1.31044e+01,
       1.29600e+01, 1.28164e+01, 1.26736e+01, 1.25316e+01, 1.23904e+01,
       1.22500e+01, 1.21104e+01, 1.19716e+01, 1.18336e+01, 1.16964e+01,
       1.15600e+01, 1.14244e+01, 1.12896e+01, 1.11556e+01, 1.10224e+01,
       1.08900e+01, 1.07584e+01, 1.06276e+01, 1.04976e+01, 1.03684e+01,
       1.02400e+01, 1.01124e+01, 9.98560e+00, 9.85960e+00, 9.73440e+00,
       9.61000e+00, 9.48640e+00, 9.36360e+00, 9.24160e+00, 9.12040e+00,
       9.00000e+00, 8.88040e+00, 8.76160e+00, 8.64360e+00, 8.52640e+00,
       8.41000e+00, 8.29440e+00, 8.17960e+00, 8.06560e+00, 7.95240e+00,
       7.84000e+00, 7.72840e+00, 7.61760e+00, 7.50760e+00, 7.39840e+00,
       7.29000e+00, 7.18240e+00, 7.07560e+00, 6.96960e+00, 6.864

In [16]:
V_square=pd.DataFrame(V_square)
V_square.columns = ['V_square']
V_square

V_square
0     16.0000
1     15.8404
2     15.6816
3     15.5236
4     15.3664
..        ...
196    0.0064
197    0.0036
198    0.0016
199    0.0004
200    0.0000

[201 rows x 1 columns]

In [17]:
task3 =task2.join(V_square,lsuffix="_left")
task3

V             I           J  V_square
0    4.00  1.710000e-03  285.000000   16.0000
1    3.98  1.670000e-03  278.333333   15.8404
2    3.96  1.640000e-03  273.333333   15.6816
3    3.94  1.630000e-03  271.666667   15.5236
4    3.92  1.610000e-03  268.333333   15.3664
..    ...           ...         ...       ...
196  0.08  1.240000e-06    0.206667    0.0064
197  0.06  8.940000e-07    0.149000    0.0036
198  0.04  5.830000e-07    0.097167    0.0016
199  0.02  2.870000e-07    0.047833    0.0004
200  0.00  1.040000e-10    0.000017    0.0000

[201 rows x 4 columns]

In [18]:
log_v = np.log10(V, out=V, where=V> 0)
log_v

array([ 0.60205999,  0.59988307,  0.59769519,  0.59549622,  0.59328607,
        0.59106461,  0.58883173,  0.5865873 ,  0.58433122,  0.58206336,
        0.5797836 ,  0.5774918 ,  0.57518784,  0.5728716 ,  0.57054294,
        0.56820172,  0.56584782,  0.56348109,  0.56110138,  0.55870857,
        0.5563025 ,  0.55388303,  0.55145   ,  0.54900326,  0.54654266,
        0.54406804,  0.54157924,  0.5390761 ,  0.53655844,  0.53402611,
        0.53147892,  0.5289167 ,  0.52633928,  0.52374647,  0.52113808,
        0.51851394,  0.51587384,  0.5132176 ,  0.51054501,  0.50785587,
        0.50514998,  0.50242712,  0.49968708,  0.49692965,  0.49415459,
        0.49136169,  0.48855072,  0.48572143,  0.48287358,  0.48000694,
        0.47712125,  0.47421626,  0.47129171,  0.46834733,  0.46538285,
        0.462398  ,  0.45939249,  0.45636603,  0.45331834,  0.45024911,
        0.44715803,  0.4440448 ,  0.44090908,  0.43775056,  0.4345689 ,
        0.43136376,  0.42813479,  0.42488164,  0.42160393,  0.41

In [19]:
log_v=pd.DataFrame(log_v)
log_v.columns = ['log_v']
log_v

log_v
0    0.602060
1    0.599883
2    0.597695
3    0.595496
4    0.593286
..        ...
196 -1.096910
197 -1.221849
198 -1.397940
199 -1.698970
200  0.000000

[201 rows x 1 columns]

In [20]:
task4 =task3.join(log_v,lsuffix="_left")
task4

V             I           J  V_square     log_v
0    4.00  1.710000e-03  285.000000   16.0000  0.602060
1    3.98  1.670000e-03  278.333333   15.8404  0.599883
2    3.96  1.640000e-03  273.333333   15.6816  0.597695
3    3.94  1.630000e-03  271.666667   15.5236  0.595496
4    3.92  1.610000e-03  268.333333   15.3664  0.593286
..    ...           ...         ...       ...       ...
196  0.08  1.240000e-06    0.206667    0.0064 -1.096910
197  0.06  8.940000e-07    0.149000    0.0036 -1.221849
198  0.04  5.830000e-07    0.097167    0.0016 -1.397940
199  0.02  2.870000e-07    0.047833    0.0004 -1.698970
200  0.00  1.040000e-10    0.000017    0.0000  0.000000

[201 rows x 5 columns]